### ISSUE TITLE
Variables incorrectly resolved in cross junction include files

### ISSUE THREAD

**Issue by gtristan** [apache/buildstream#1485]
We solved the issue where project options were being resolved in the wrong context when conditional statements were loaded from cross junction include files... it appears we still have the same problem for variables.

What I have observed:

* freedesktop-sdk declares the `target_arch` project option, which automatically assigns the `arch` *variable*
* freedesktop-sdk provides the [include/arch.yml](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/include/arch.yml) include file
  * This file will start off declaring some variables like triplet: `%{arch}-unknown-linux-%{abi}`
* My project which uses freedesktop-sdk also declares a `target_arch` project option, **but** this is locally exported as the `target_arch` variable in my project
* My project then goes on to include [include/arch.yml](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/include/arch.yml) from freedesktop-sdk

Then, when I build a local element which indirectly depends on fdsdk elements, I get the following error:

```
freedesktop-sdk.bst:freedesktop-sdk.bst:include/_private/arch.yml [line 6 column 10]: Reference to undefined variable 'arch'
```

This leads me to suspect that when including the `arch.yml` file locally, it is trying to resolve it's variables using the *including* project's context, rather than the *included* projects context.

### Possibly unrelated

If I try to build the cross-junction element directly, with e.g.:

```shell
bst build freedesktop-sdk.bst:bootstrap/export-bootstrap.bst
```

Then I get a *different* error:

```
freedesktop-sdk.bst:freedesktop-sdk.bst:include/_private/arch.yml [line 13 column 2]: Failed to evaluate expression (target_arch == "i686"): 'target_arch' is undefined
```

**Comment by gtristan** [comment]
> This leads me to suspect that when including the `arch.yml` file locally, it is trying to resolve it's variables using the *including* project's context, rather than the *included* projects context.

This has been verified in my branch with this failing test:
https://github.com/apache/buildstream/blob/tristan/validate-cross-project-include-vars/tests/format/junctions.py#L822
https://github.com/apache/buildstream/tree/tristan/validate-cross-project-include-vars/tests/format/junctions/include-vars

**Comment by nanonyme** [comment]
@gtristan this same bug exists for bst1.
