### ISSUE TITLE
Support compression of logs through user configuration

### ISSUE THREAD

**Issue by nanonyme** [apache/buildstream#1527]
BuildStream element full logs can be rather large, especially when it comes to CI. It would be nice to have an option that would compress them by default so they would be smaller artifacts from CI.

**Comment by gtristan** [comment]
Is there a reason why such a feature should be baked into the tool itself, instead of simply compressing (and possibly tarring up) the logs directory after a build ?

**Comment by nanonyme** [comment]
That is precisely what I'm planning to do but it seems as if this might benefit other workloads too. Eg Mesa build log seemed to be around 10 megabytes. When you multiply this with a lot of elements, you get large space usage. There's many toolings like xzless which you can use to read through compressed logs

**Comment by gtristan** [comment]
I'm a bit torn here..

* One one hand, I think that compressing the logs in the log directory is not mission specific. The project benefits from avoiding handling use cases that can be handled separately
* On the other hand, log files are actually cached in the artifact (e.g. `bst artifact log` displays them, even if you `rm -rf` your log directory)

Instead, I'm more inclined to suggest that:
* We stop saving logs to the log directory, and remove the concept of the *logs* directory completely
  * This would require a bit of a change in the UI, which refers to log paths, which instead could be delivered through `bst artifact log` on demand (and is already suggested on the command prompt in the case of interactive failed builds)
* We compress logs stored in the artifact unconditionally
* If you want to capture the logs for a specific build graph after a successful build, you can use `bst artifact log` to capture them and compress them in whatever format you want (for the purpose of say, gitlab pipeline artifacts)

**Comment by nanonyme** [comment]
To be fair, failure logs are at least as important if not more so than logs for successful build.

**Comment by gtristan** [comment]
> To be fair, failure logs are at least as important if not more so than logs for successful build.

Indeed, and artifacts for failed builds are only optionally cached.

probably we should ensure that we cache the failed build artifacts unconditionally, and only make pushing failed build artifacts optional.

**Comment by nanonyme** [comment]
Maybe it's better just doing this by consumer after bst.
