### ISSUE TITLE
Broken links in BuildStream documentation

### ISSUE THREAD

**Issue by ghost** [apache/buildstream#1538]
I read online documentation to install BuildStream and found some broken / outdated links.

 1. https://docs.buildstream.build/1.6.1/install_docker.html - links to https://hub.docker.com/r/buildstream/buildstream-fedora which no longer exists.

 2. https://docs.buildstream.build/1.6.1/index.html - obsolete links to https://gitlab.com/BuildStream/buildstream and https://gitlab.com/BuildStream/buildstream/issues

**Comment by gtristan** [comment]
This should be fixed by #1539 

But we still have issues publishing the docs (or rather we do again), see https://gitlab.com/BuildStream/docs-website/-/pipelines

**Comment by gtristan** [comment]
These publishing issues have since been fixed, closing this.

**Comment by cs-shadow** [comment]
> These publishing issues have since been fixed, closing this.

I am assuming that you meant to close this and missed to hit the close button, closing for real :)
