### ISSUE TITLE
Buildstream not picking up default-mirrors

### ISSUE THREAD

**Issue by EllisBarnwell** [apache/buildstream#1542]
After setting the default-mirror property in ~/.config/buildstream.conf and then running bst track, buildstream appears to pick up on the upstream source rather than the mirror location.

**Comment by gtristan** [comment]
Hi,

As specified in [the docs](https://docs.buildstream.build/1.6.1/format_project.html#mirrors):

> The order that the mirrors (and the URIs therein) are consulted is in the order they are defined when fetching, and in reverse-order when tracking.

The rationale here is that when tracking new sources you probably want to consult the original upstream first, and then roll over to mirrors you may have setup in the case that the upstream is not reachable at tracking time - while the opposite is true while fetching, when you want the most efficient route taken during regular builds.

**Comment by EllisBarnwell** [comment]
Ok. Are you saying that setting the defualt-mirror property only has an effect when fetching and not when tracking?

**Comment by gtristan** [comment]
> Ok. Are you saying that setting the defualt-mirror property only has an effect when fetching and not when tracking?

In practice the effect is that the `default-mirror` will be observed *last* when tracking and *first* when fetching.

There is not much control as to what URIs should be accessed in `bst-1` which should be changing presently in master after merging #1537 (see the [proposal](https://lists.apache.org/api/source.lua?id=1w3s72q4yf23rx0yc57tw0lf94q3g5bj) this is implementing for a better overview of what this branch does).

By itself, the above branch should address this problem in a way that is flexible for different projects' workflows, but this raises the question as to whether we should also revert this list reversal in master, as this additional control removes the need for reversing the lists (which in *general*, ensures that we consult upstreams before local mirrors when tracking, ensuring that we get the bleeding edge as expected when we track).

**Comment by gtristan** [comment]
I think this question has been sufficiently answered so I'm closing this for now, feel free to reopen this if you feel this requires further discussion.
