### ISSUE TITLE
RISC-V architecture not supported in bst master

### ISSUE THREAD

**Issue by jjardon** [apache/buildstream#1578]
Error in freedesktop-sdk when trying to build with bst master (bst-1 is fine): https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/jobs/2012261945

**Comment by jjardon** [comment]
@gtristan @abderrahim  can we please add this to  https://github.com/apache/buildstream/milestone/3 ? fdsdk will not be able to build without this

**Comment by juergbi** [comment]
I've opened https://github.com/bazelbuild/remote-apis/pull/227 to update the REAPI platform lexicon.

**Comment by jjardon** [comment]
Corresponding PR for buildstream for when above gets merged here: https://github.com/apache/buildstream/pull/1670

**Comment by juergbi** [comment]
Merged.
