### ISSUE TITLE
BuildStream 1.6.4 stable release

### ISSUE THREAD

**Issue by ghost** [apache/buildstream#1584]
I want to use .netrc support in `bst-1` branch and would like this in a stable Bst release.

List of outstanding bugfix MRs we should look at before releasing.

  * https://github.com/apache/buildstream/pull/1563

**Comment by abderrahim** [comment]
Other MRs to consider before release:
* https://github.com/apache/buildstream/pull/1564
* https://github.com/apache/buildstream/pull/1567
* https://github.com/apache/buildstream/pull/1568
* https://github.com/apache/buildstream/pull/1575
* https://github.com/apache/buildstream/pull/1562 (This one fixes #1495 for bst-1 by limiting the version of ruamel.yaml)

**Comment by gtristan** [comment]
I've merged some of these which appear mostly harmless and straight forward.

I accidentally merged #1564 so now we have broken CI in `bst-1`, I'm hoping we can fix this in #1562 rather than having to revert that change.

I'm not entirely sure off hand whether to merge #1575 or not.

**Comment by sam-thursfield-nutanix** [comment]
Related: https://github.com/apache/buildstream/issues/1588

**Comment by nanonyme** [comment]
https://github.com/apache/buildstream/pull/1576 would also be great to be integrated if no objections. It's blocking us from fixing sandbox arch in freedesktop-sdk.

**Comment by gtristan** [comment]
Released [today](https://lists.apache.org/thread/5gcmk0bwr9qc192x1do2dhljrblnz2q6).
