### ISSUE TITLE
Consider adding symlink `/proc/self/fds` -> `/dev/fds` in sandbox

### ISSUE THREAD

**Issue by ghost** [apache/buildstream#1610]
Using Bst 1.6.4 to wrap the test suite of a proprietary component I am working on.

The tests are run using a command similar to this.

```
/bin/bash "-c" "/bin/mkdir -p ${TEST_OUTPUT}/mytest mytest > >(tee ${TEST_OUTPUT}/mytest/stdout.log) 2> >(tee ${TEST_OUTPUT}/mytest/stderr.log >&2)"
```

Bash version in the sandbox is 4.2.26.

The tests all fail when run inside `bst build`, with this error:

```
/bin/bash: /dev/fd/62: No such file or directory
```

Bash tries to use `/dev/fd` for the `>()` redirects, and this fails as it does not exist.

I found an old newsgroup post saying that this is by design: https://gnu.bash.bug.narkive.com/waCuOLkA/dev-fd-62-no-such-file-or-directory. I haven't tested if newer Bash versions have the same issue.

Workaround:

  * Run the tests in `bst shell` instead, so the `/dev` from the host is bind-mounted with its `/dev/fd` symlink
  * Use a custom element plugin to run the tests, which can set `SandboxFlags.INTERACTIVE` and get the same effect as above.

Not possible:

  * Create the `/dev/fd` symlink in the sandbox - /dev is readonly.

Proposed solution:

  * Make a `/dev/fd` symlink in every sandbox. It seems harmless and would prevent this strange breakage when using Bash shell.

**Comment by nanonyme** [comment]
Hmm, I don't think that "not possible" part is true. See https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/components/standard-streams.bst. This seems like a useful thing to have still though, similar to standard streams.

**Comment by nanonyme** [comment]
Related to https://github.com/apache/buildstream/issues/1373

**Comment by nanonyme** [comment]
https://gitlab.com/BuildGrid/buildbox/buildbox-run-bubblewrap/-/issues/7 is the right place for this

**Comment by nanonyme** [comment]
@ssssam I don't expect this to be fixed for BuildStream 1. It's now fixed on BuildStream 2.

**Comment by ghost** [comment]
Good enough for me, let's close.
