### ISSUE TITLE
[bst-1] Depend on new version of ruamel.yaml

### ISSUE THREAD

**Issue by FantasqueX** [apache/buildstream#1623]
Hi there! I would like to upgrade buildstream package in AUR. However I find that the most recent stable version depends on `ruamel.yaml < 0.17` which conflicts with [python-ruamel-yaml](https://archlinux.org/packages/community/any/python-ruamel-yaml/) in ArchLinux repository. The depends in master branch remove the restriction. I hope there will be a new stable version removing the restriction to make packaging a possible thing.

**Comment by abderrahim** [comment]
The master branch does have the same problem (that is #1495) when run with recent versions of ruaml.yaml. I have a pull request (#1546) to fix the issue on master, but I'm not intending to do the same fix for bst-1 as the code is different, so we added the version limit.

**Comment by jjardon** [comment]
This is now a problem for fedora 37 as well: https://bugzilla.redhat.com/show_bug.cgi?id=2090763

**Comment by nanonyme** [comment]
Not fixing bst1 has a risk Fedora will eventually remove BuildStream package, possibly by next October.

**Comment by gtristan** [comment]
Fixed by #1709
