### ISSUE TITLE
infra: stable links for documentation

### ISSUE THREAD

**Issue by sam-thursfield-nutanix** [apache/buildstream#1628]
I want to link to BuildStream stable documentation, so I go to https://docs.buildstream.build/, select '1.6.4' in the list of versions, and the URL is: https://docs.buildstream.build/1.6.4/index.html

I paste that in internal documentation wiki where I want to link to upstream documentation and all is fine.

Then BuildStream 1.6.5 is released and the https://docs.buildstream.build/1.6.4/index.html link becomes invalid, now someone needs to update https://docs.buildstream.build/1.6.5/index.html in the documentation.

Can we have a stable URL to the docs, so I can link to specific pages rather than only being able to link to https://docs.buildstream.build/ ? Some sort of link like `https://docs.buildstream.build/stable/` would be nice.

**Comment by gtristan** [comment]
This is fixed by https://gitlab.com/BuildStream/docs-website/-/merge_requests/9

Now docs are published to locations which exclude the micro point version, e.g.: https://docs.buildstream.build/1.6/index.html
