### ISSUE TITLE
Documentation from latest tag (1.95.0) master is not being published at https://docs.buildstream.build/

### ISSUE THREAD

**Issue by jjardon** [apache/buildstream#1661]

**Comment by gtristan** [comment]
It looks like docs.tgz was not generated in CI for https://github.com/apache/buildstream/releases/tag/1.95.0

**Comment by gtristan** [comment]
This happened because the release was published in advance of merging #1657

**Comment by gtristan** [comment]
I've manually fixed this for the 1.95.0 release, docs are up at: https://docs.buildstream.build/1.95/index.html
