### ISSUE TITLE
bst2: CASCacheError: Timed out waiting for buildbox-casd to become ready

### ISSUE THREAD

**Issue by jjardon** [apache/buildstream#1681]
Some examples of this failure here:
- https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/jobs/2681685721
- https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/jobs/2687429185

This probably affects buildbox-casd, but as the timeouts are set by buildstream, we decided the primary issue to track this should be here

Downstream issue: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1444

**Comment by jjardon** [comment]
For reference, some performance improvements that have alleviate the situation but not completely fixed it:
- https://github.com/apache/buildstream/pull/1678
- https://github.com/apache/buildstream/pull/1677
- https://github.com/apache/buildstream/pull/1680

**Comment by nanonyme** [comment]
15 second timeout between sigterm and sigkill also seems a bit on the low side since it actually triggering will result in issues starting BuildStream next time. How about bumping this to one minute?

**Comment by juergbi** [comment]
Bumping the timeout may be reasonable as it may prevent issues on next start, and BuildStream at least already mentions what it's doing.

However, we should still improve the underlying issue. @abderrahim mentioned that a likely cause is BuildStream attempting to terminate buildbox-casd when buildbox-casd is in the middle of cache expiry and I agree. If that's indeed the case, we should modify buildbox-casd to stop cache expiry when receiving SIGTERM.

**Comment by nanonyme** [comment]
Yeah, I wasn't suggesting not fixing the actual performance issues.

**Comment by juergbi** [comment]
https://gitlab.com/BuildGrid/buildbox/buildbox-casd/-/merge_requests/274 should reduce buildbox-casd shutdown time in case of running cleanup.

**Comment by nanonyme** [comment]
I'm leaning towards backporting the fix for freedesktop-sdk Docker images CI while we wait for merge and release. We seem to be still losing pipelines due to random errors when there's load.

**Comment by nanonyme** [comment]
@jjardon I guess this can be closed now?

**Comment by jjardon** [comment]
I think so, yes

**Comment by nanonyme** [comment]
@jjardon I think you have permissions to close as the creator.
