### ISSUE TITLE
Documentation doesn't link to buildstream-plugins

### ISSUE THREAD

**Issue by abderrahim** [apache/buildstream#1747]
Trying to find the autotools documentation, I landed here: https://docs.buildstream.build/master/core_plugins.html

It specifies plugins that are still in core, and links to external plugins (experimental and container) but not to official buildstream-plugins.

**Comment by jjardon** [comment]
@abderrahim I think this is fixed now? https://docs.buildstream.build/master/core_plugins.html#external-plugins

**Comment by abderrahim** [comment]
Indeed.
