### ISSUE TITLE
Can we use buildstream1 junctions from buildstream2

### ISSUE THREAD

**Issue by itsManjeet** [apache/buildstream#1767]
As per the docs https://docs.buildstream.build/ it advise to use build-stream 2 for new project. but Is it possible to use other project as junctions inside the new one.
on default configurations it throw me a error

```
gnome.bst:project.conf [line 2 column 0]: Dictionary did not contain expected key 'min-version'
```
basically its expecting a buildstream 2 project.conf i guess

## How to reproduce
- Setup a build-stream 2 project
- Create junction and import package from either gnome-build-meta `master` or freedesktop-sdk `22.x` branch (however freedesktop-sdk `master` working as its using buildstream 2).

**Comment by abderrahim** [comment]
Indeed, you can't. If you use another project via a junction, you need to use the same bst version.
