### ISSUE TITLE
Unclear output from BuildStream when translate_url called twice with different URL's as primary

### ISSUE THREAD

**Issue by nanonyme** [apache/buildstream#1783]
BuildStream in this case hits assert (bad because this might get optimized out, we should instead aise non-retryable SourceError) and also we must add better error context with the variables to make it possible to debug plugin bugs. https://github.com/apache/buildstream/blob/master/src/buildstream/source.py#L754

**Comment by gtristan** [comment]
Not SourceError as that is for recoverable user facing errors. Instead we want an error not derived from BstError so as to ensure the desired BUG message and stack trace which is more useful for plugin authors in this case.

indeed we should refactor our asserts to use perhaps a generic Bug() exception instead.
