### ISSUE TITLE
The `mypy` checks in CI are now failing

### ISSUE THREAD

**Issue by gtristan** [apache/buildstream#1796]
The `mypy` checks in CI fail with the following:

```
mypy run-test: commands[0] | mypy
src/buildstream/utils.py:47: error: Library stubs not installed for "google.protobuf" (or incompatible with Python 3.10)
src/buildstream/storage/_casbaseddirectory.py:26: error: Library stubs not installed for "google.protobuf" (or incompatible with Python 3.10)
src/buildstream/storage/_casbaseddirectory.py:26: note: Hint: "python3 -m pip install types-protobuf"
src/buildstream/storage/_casbaseddirectory.py:26: note: (or run "mypy --install-types" to install all missing stub packages)
src/buildstream/storage/_casbaseddirectory.py:26: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 2 errors in 2 files (checked 186 source files)
ERROR: InvocationError for command /home/testuser/buildstream/.tox/mypy/bin/mypy (exited with code 1)
```
They pass perfectly fine with python3.9, but for some reason we are running them with python 3.10 which perhaps is not yet mature enough.

**Comment by cs-shadow** [comment]
@gtristan is this issue still relevant?

I can see that this pipeline from a couple months back is passing mypy checks - https://github.com/apache/buildstream/actions/runs/4499768440/jobs/8204842204?pr=1834

**Comment by abderrahim** [comment]
This started failing again recently (the test is now running on python 3.11). I fixed it by pinning the version of types-protobuf and friends https://github.com/apache/buildstream/pull/1900.

Closing this as it should hopefully not happen again.
