### ISSUE TITLE
buildstream2 is not compatible with python 3.11

### ISSUE THREAD

**Issue by jjardon** [apache/buildstream#1802]
Issue for bst1: https://github.com/apache/buildstream/issues/1758

**Comment by nanonyme** [comment]
@gtristan @abderrahim so here we could probably give that grpclib alternative consideration. Looks like Python 3.7+ requirement is fine https://pypi.org/project/BuildStream/

**Comment by nanonyme** [comment]
BuildStream 2 is now tested on Python 3.11. There is not yet a release with Python 3.11 support. I am hoping since making releases is so hard that the release would also contain fix for https://github.com/apache/buildstream/issues/1821

**Comment by nanonyme** [comment]
This should now be closed.
