### ISSUE TITLE
Add flag to allow building despite cached failure

### ISSUE THREAD

**Issue by nanonyme** [apache/buildstream#1818]
Context:

In CI there can be random events which results in can break build like running out of disk space. When shared CAS is used, such failures are cached and persisted. This makes project work impossible until the bad entry from CAS is purged 

Spec:

As per discussion by @juergbi failure logs are tied to caching failures. So the best approach seems to be to provide a switch for build (and corresponding option in user config) that makes BuildStream ignore cached failures. Cached successful builds must be used as normal. It build succeeds, the new successful artifact must replace the old failure artifact in shared CAS.

**Comment by abderrahim** [comment]
I believe this is a duplicate of https://github.com/apache/buildstream/issues/1335

**Comment by nanonyme** [comment]
Okay, I will close this one, the previous had a lot of design discussion.

**Comment by nanonyme** [comment]
@abderrahim it's not clear from title of the other issue that it's not about interactive builds.

**Comment by abderrahim** [comment]
It's pretty clear from the title "Can not retry job in non interactive mode" that it's about non-interactive builds (although it could indeed use a dash)

**Comment by nanonyme** [comment]
Hm, I must have misread.
