### ISSUE TITLE
BuildStream 2.0.0 includes buildbox-fuse that fails gnulib sanity tests

### ISSUE THREAD

**Issue by nanonyme** [apache/buildstream#1821]
This results in incorrect code (multiple compatibility functions) to be generated for projects that use gnulib. buildbox-fuse issues https://gitlab.com/BuildGrid/buildbox/buildbox-fuse/-/issues/45 https://gitlab.com/BuildGrid/buildbox/buildbox-fuse/-/issues/46

**Comment by nanonyme** [comment]
This is also a BuildStream bug because BuildStream wheels include buildbox-fuse.

**Comment by juergbi** [comment]
The buildbox-fuse fix is included in https://gitlab.com/BuildGrid/buildbox/buildbox-integration/-/releases/0.0.65, which will be picked up by BuildStream CI when building the wheels.

**Comment by nanonyme** [comment]
@juergbi I'm talking here of the new wheels created by this repo that people install with pip. BuildStream must make release 2.0.1 to fix this.

**Comment by nanonyme** [comment]
See https://pypi.org/project/BuildStream/2.0.0/, wheels here bundle buildbox components.

**Comment by juergbi** [comment]
Yes, a new BuildStream release is required. However, CI builds the release tarballs and wheels and should automatically pick up the latest buildbox-integration release. We will hopefully have a new release prepared by the end of the week.

**Comment by taozuhong** [comment]
@juergbi Could BuildStream will support to build [Vala](https://gitlab.gnome.org/GNOME/vala) project?

**Comment by nanonyme** [comment]
Both freedesktop-sdk and gnome-build-meta routinely build vala inside Buildstream. That seems offtopic from this issue.
