### ISSUE TITLE
Buildstream virtual environment packages missing

### ISSUE THREAD

**Issue by Tanvir786123** [apache/buildstream#1870]
### Context
When using the `pip install Buildstream` command inside a **venv**, there are still missing packages that require manual installation. For **example**, one needs to **manually** install:
- tomli
- packaging
- dulwich
- requests

### Description
We need to ensure that all required dependencies are installed through the  `pip install Buildstream` command.

### Acceptance Criteria
- We use a **fresh** VM
- We run the `pip install Buildstream` command
- We **confirm** that we can run the `bst build` command against a large project, e.g., [gnome-build-meta](https://gitlab.gnome.org/GNOME/gnome-build-meta)

CC:
- @jjardon 
- @abderrahim 
- @nanonyme

**Comment by Tanvir786123** [comment]
Closing because the official [site](https://buildstream.build/install.html) does indeed state:

```
Some host packages are required which Pip cannot provide, see the list in the reference manual's ["Installing Dependencies" section](https://docs.buildstream.build/master/main_install.html#installing-dependencies).
```

**Comment by nanonyme** [comment]
These are specifically packages various plugins need. tomli is by cargo (except on Python 3.11 and newer), packaging is by pypi, dulwich is by git_repo and requests by Docker source plugin.
