### ISSUE TITLE
Bundled buildbox priority higher than from PATH

### ISSUE THREAD

**Issue by nanonyme** [apache/buildstream#1873]
This makes it very inconvenient to replace bundled buildbox with more up to date one from buildbox-integration. Bundled is always considered highest priority and there is no way to install the wheel without also getting bundled buildbox since it's not split to extras and separate package. https://github.com/apache/buildstream/blob/master/src/buildstream/utils.py#L734

**Comment by gtristan** [comment]
I tend to agree, if the user has installed buildbox separately we should respect the user's choice (while implementing runtime minimal bound dependency checks as needed).

As a workaround, I think the following should work:

```
pip install --no-binary BuildStream BuildStream
```

This approach will require a host compiler and host cython but that's fairly reasonable for a developer's computer.
