### ISSUE TITLE
BuildStream calling buildbox-run instead of buildbox-run-bubblewrap

### ISSUE THREAD

**Issue by nanonyme** [apache/buildstream#1942]
BuildStream is invoking non-existing binary (by default) from buildbox project called buildbox-run. It actually expects this to be a symlink to buildbox-run-bubblewrap. BuildStream most likely should instead invoke buildbox-run-bubblewrap directly.

**Comment by juergbi** [comment]
buildbox-run-bubblewrap is Linux-specific and, at least theoretically, other sandbox runner implementations could be used also on Linux. E.g. buildbox-run-userchroot works on Linux, although there are limitations compared to buildbox-run-bubblewrap.

Improvements in this area may be possible but simply hardcoding buildbox-run-bubblewrap in BuildStream would be a hack, not a sensible solution.

It would be reasonable for BuildBox distro packages to create that symlink.

**Comment by nanonyme** [comment]
I will create ticket on buildbox and close this.

**Comment by nanonyme** [comment]
Closing in favor of https://gitlab.com/BuildGrid/buildbox/buildbox/-/issues/173
